### ISSUE TITLE
Not all listed models work

### ISSUE THREAD

**Issue by Beenhakker** [Ngz91/Eunomia#1]
Hi,

First off: thanks for this. Exactly what I wanted to build myself.

Second: not all listed models seem to be working on my Mac (Intel).

**Working**:
1. ggml-gpt4all-j-v1.3-groovy.bin

**Not working**: (gptj_model_load: invalid model file (bad magic))
1. ggml-gpt4all-l13b-snoozy.bin
2. ggml-nous-gpt4-vicuna-13b.bin

**Comment by Ngz91** [comment]
Hello, after testing locally on a Windows machine (Don't have access to a Mac) I was able to replicate the error with `ggml-nous-gpt4-vicuna-13b.bin`.

![badMagicError](https://github.com/Ngz91/Eunomia/assets/74746611/2fffeb82-4bb8-472f-8968-f7ebe63b0e37)

 I suspect that it could be the backend that you are using when loading the model. In my case I tried to load the model using the `gptj` backend, but it only works with the `llama` backend. 

Try changing the backend and let me know if that solves your problem.
